export const cartTypes = {
  VIEW_CART: 'VIEW_CART',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_CART',
  CONFIRM_ORDER: 'CONFIRM_ORDER',
  ADD_QUANTITY: 'ADD_QUANTITY',
  SUBSTRACT_QUANTITY: 'SUBSTRACT_QUANTITY'
};